# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: pushToDocker
    displayName: pushToDocker
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'annelaure42/brief14myappdevops'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Simplon ARA Lyon Admin Cloud P22(393e3de3-0900-4b72-8f1b-fb3b1d6b97f1)'
        backendAzureRmResourceGroupName: 'anne_group'
        backendAzureRmStorageAccountName: 'annestoragebrief14'
        backendAzureRmContainerName: 'blob2'
        backendAzureRmKey: 'tf'
      
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'Simplon ARA Lyon Admin Cloud P22(393e3de3-0900-4b72-8f1b-fb3b1d6b97f1)'

