trigger:
  - main
resources:
  - repo: self
stages:
  stages:
  displayName: Build image
  jobs:
  - job: pushToDocker
    displayName: pushToDocker
    - task: Docker@2
      inputs:
      containerRegistry: 'docker'
      repository: 'annelaure42/brief14myappdevops'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'