# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

stages:
  jobs:
  - job:
    steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'docker'
      repository: 'annelaure42/brief14myappdevops'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'