-trigger:
  - main
resources:
  - repo: self
stages:
  stage:
  - task: Docker@2
    inputs:
    containerRegistry: 'docker'
    repository: 'annelaure42/brief14myappdevops'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'